# Generated by Django 5.2.15 on 2026-07-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_phase1_phase2_hr_rbac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdiscipline',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('resolved', 'Resolved'), ('open', 'Open')], default='open', max_length=20),
        ),
    ]
