"""Hostel workflow and status constants."""
from __future__ import annotations

ALLOCATION_PENDING = "pending"
ALLOCATION_ACTIVE = "active"
ALLOCATION_CHECKED_IN = "checked_in"
ALLOCATION_CHECKED_OUT = "checked_out"
ALLOCATION_VACATED = "vacated"

ALLOCATION_STATUSES = frozenset({
    ALLOCATION_PENDING,
    ALLOCATION_ACTIVE,
    ALLOCATION_CHECKED_IN,
    ALLOCATION_CHECKED_OUT,
    ALLOCATION_VACATED,
})

ALLOCATION_OCCUPYING_STATUSES = frozenset({
    ALLOCATION_ACTIVE,
    ALLOCATION_CHECKED_IN,
    ALLOCATION_CHECKED_OUT,
})

MAINTENANCE_REPORTED = "reported"
MAINTENANCE_IN_PROGRESS = "in_progress"
MAINTENANCE_COMPLETED = "completed"
MAINTENANCE_CANCELLED = "cancelled"

MAINTENANCE_STATUSES = frozenset({
    MAINTENANCE_REPORTED,
    MAINTENANCE_IN_PROGRESS,
    MAINTENANCE_COMPLETED,
    MAINTENANCE_CANCELLED,
})

MAINTENANCE_OPEN_STATUSES = frozenset({
    MAINTENANCE_REPORTED,
    MAINTENANCE_IN_PROGRESS,
})

VISITOR_CHECKED_IN = "checked_in"
VISITOR_CHECKED_OUT = "checked_out"

VISITOR_STATUSES = frozenset({
    VISITOR_CHECKED_IN,
    VISITOR_CHECKED_OUT,
})

DISCIPLINE_OPEN = "open"
DISCIPLINE_RESOLVED = "resolved"
DISCIPLINE_ESCALATED = "escalated"

DISCIPLINE_STATUSES = frozenset({
    DISCIPLINE_OPEN,
    DISCIPLINE_RESOLVED,
    DISCIPLINE_ESCALATED,
})

HOSTEL_FEE_PENDING = "pending"
HOSTEL_FEE_PARTIAL = "partial"
HOSTEL_FEE_PAID = "paid"
HOSTEL_FEE_OVERDUE = "overdue"

HOSTEL_FEE_STATUSES = frozenset({
    HOSTEL_FEE_PENDING,
    HOSTEL_FEE_PARTIAL,
    HOSTEL_FEE_PAID,
    HOSTEL_FEE_OVERDUE,
})