# Generated by Django 5.2.15 on 2026-07-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_profile_expansion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staff',
            new_name='staff_staff_tenant__4976bc_idx',
            old_name='staff_staff_tenant__4a1c2e_idx',
        ),
        migrations.RenameIndex(
            model_name='staff',
            new_name='staff_staff_tenant__506fe2_idx',
            old_name='staff_staff_tenant__9f3b1a_idx',
        ),
        migrations.AlterField(
            model_name='staff',
            name='portal_role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('school_admin', 'School Admin'), ('head_teacher', 'Head Teacher'), ('deputy_head_teacher', 'Deputy Head Teacher'), ('director_of_studies', 'Director of Studies'), ('head_of_department', 'Head of Department'), ('teacher', 'Teacher'), ('class_teacher', 'Class Teacher'), ('parent', 'Parent'), ('student', 'Student'), ('bursar', 'Bursar / Accountant'), ('assistant_bursar', 'Assistant Bursar'), ('librarian', 'Librarian'), ('hr_manager', 'Human Resource Manager'), ('transport_manager', 'Transport Manager'), ('hostel_manager', 'Hostel Manager'), ('inventory_manager', 'Inventory Manager / Store Keeper'), ('finance_officer', 'Finance Officer (Legacy)'), ('hr_officer', 'HR Officer (Legacy)'), ('transport_officer', 'Transport Officer (Legacy)'), ('hostel_warden', 'Hostel Warden (Legacy)'), ('inventory_officer', 'Inventory Officer (Legacy)'), ('receptionist', 'Receptionist'), ('nurse', 'Nurse'), ('counselor', 'Counselor')], db_index=True, default='teacher', help_text='Dashboard role assigned when portal access is enabled', max_length=30),
        ),
    ]
