# Generated by Django 5.2.15 on 2026-07-01 06:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_used_mb', models.PositiveIntegerField(default=0)),
                ('storage_cap_mb', models.PositiveIntegerField(default=1024)),
                ('failed_jobs_24h', models.PositiveIntegerField(default=0)),
                ('uptime_percent', models.DecimalField(decimal_places=3, default=100, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'Platform metrics',
            },
        ),
    ]
