# Generated by Django 5.2.15 on 2026-07-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0002_platform_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformbroadcast',
            name='audience',
            field=models.CharField(choices=[('all', 'All Schools'), ('trial', 'Trial Plans'), ('basic', 'Basic Plans'), ('premium', 'Premium Plans'), ('premium_plus', 'Premium Plus Plans'), ('active', 'Active Schools Only')], default='all', max_length=30),
        ),
        migrations.AddField(
            model_name='platformbroadcast',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformbroadcast',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='platformmetrics',
            name='customer_satisfaction_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='platformmetrics',
            name='feature_adoption_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='platformmetrics',
            name='support_resolution_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
