# Generated by Django 5.2.15 on 2026-07-01 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0004_registration_notifications'),
        ('tenants', '0002_registration_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformNotificationReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='platformnotification',
            index=models.Index(fields=['is_read', 'status'], name='platform_pl_is_read_066607_idx'),
        ),
        migrations.AddField(
            model_name='platformnotificationreceipt',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='platform.platformnotification'),
        ),
        migrations.AddField(
            model_name='platformnotificationreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_notification_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='platformnotificationreceipt',
            index=models.Index(fields=['user', 'is_read'], name='platform_pl_user_id_528cb7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='platformnotificationreceipt',
            unique_together={('notification', 'user')},
        ),
    ]
