# Generated by Django 5.2.15 on 2026-07-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0007_notification_receipt_delete"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppSetting",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("twilio", "Twilio"),
                            ("meta", "Meta Cloud API"),
                            ("africas_talking", "Africa's Talking"),
                            ("custom", "Custom"),
                        ],
                        default="meta",
                        max_length=50,
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("api_secret", models.CharField(blank=True, max_length=255)),
                ("phone_number_id", models.CharField(blank=True, max_length=50)),
                ("business_account_id", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "WhatsApp setting",
            },
        ),
        migrations.AddField(
            model_name="platformbroadcast",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platformbroadcast",
            name="channels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="platformbroadcast",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="platform_broadcasts_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="platformbroadcast",
            name="delivered_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformbroadcast",
            name="failed_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformbroadcast",
            name="recipient_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="platformbroadcast",
            name="skipped_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="platformbroadcast",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("sent", "Sent"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PlatformBroadcastDelivery",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("recipient_phone", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("provider_reference", models.CharField(blank=True, max_length=120)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="platform.platformbroadcast",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_broadcast_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_broadcast_deliveries",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="platformbroadcast",
            index=models.Index(fields=["status", "starts_at"], name="platform_pl_status__a8f3c1_idx"),
        ),
        migrations.AddIndex(
            model_name="platformbroadcast",
            index=models.Index(fields=["audience", "status"], name="platform_pl_audienc_4e2b91_idx"),
        ),
        migrations.AddIndex(
            model_name="platformbroadcastdelivery",
            index=models.Index(
                fields=["broadcast", "channel", "status"],
                name="platform_pl_broadca_7c1d42_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="platformbroadcastdelivery",
            index=models.Index(
                fields=["broadcast", "recipient"],
                name="platform_pl_broadca_9f8e33_idx",
            ),
        ),
    ]