import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { FiDownload, FiFileText } from 'react-icons/fi';
import PageHeader from '../../components/PageHeader';
import DataTable from '../../components/DataTable';
import StatusBadge from '../../components/StatusBadge';
import { reportsService } from '../../services/moduleService';

const MOCK_REPORTS = [
  { id: 1, name: 'Student Enrollment Report', type: 'Academic', generated_at: '2026-06-30', generated_by: 'School Admin', status: 'active' },
  { id: 2, name: 'Fee Collection Summary', type: 'Finance', generated_at: '2026-06-28', generated_by: 'School Admin', status: 'active' },
  { id: 3, name: 'Attendance Monthly Report', type: 'Academic', generated_at: '2026-06-25', generated_by: 'School Admin', status: 'active' },
  { id: 4, name: 'Staff Payroll Report', type: 'HR', generated_at: '2026-06-01', generated_by: 'School Admin', status: 'active' },
];

const REPORT_TYPES = ['Academic', 'Finance', 'HR', 'Attendance', 'Inventory'];

export function Reports() {
  const [typeFilter, setTypeFilter] = useState('');

  const { data, isLoading } = useQuery({
    queryKey: ['reports', typeFilter],
    queryFn: async () => {
      try {
        const result = await reportsService.list({ type: typeFilter });
        return result?.results || result || [];
      } catch {
        return typeFilter ? MOCK_REPORTS.filter((r) => r.type === typeFilter) : MOCK_REPORTS;
      }
    },
  });

  return (
    <div>
      <PageHeader
        title="Reports"
        subtitle="Generate and download school reports"
        actions={
          <button className="btn btn-primary d-flex align-items-center gap-2">
            <FiFileText /> Generate Report
          </button>
        }
      />
      <DataTable
        columns={[
          { key: 'name', label: 'Report Name', accessor: 'name', sortable: true },
          { key: 'type', label: 'Type', accessor: 'type' },
          { key: 'generated_at', label: 'Generated', accessor: 'generated_at' },
          { key: 'generated_by', label: 'Generated By', accessor: 'generated_by' },
          { key: 'status', label: 'Status', render: (row) => <StatusBadge status={row.status} /> },
          { key: 'download', label: '', render: () => (
            <button className="btn btn-sm btn-outline-primary"><FiDownload size={14} /></button>
          )},
        ]}
        data={data || []}
        loading={isLoading}
        filters={
          <select
            className="form-select form-select-sm"
            style={{ width: 160 }}
            value={typeFilter}
            onChange={(e) => setTypeFilter(e.target.value)}
          >
            <option value="">All Types</option>
            {REPORT_TYPES.map((t) => <option key={t} value={t}>{t}</option>)}
          </select>
        }
      />
    </div>
  );
}

export default Reports;