# Generated by Django 5.2.15 on 2026-07-04 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_subjectpaper'),
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='paper',
            field=models.ForeignKey(blank=True, help_text='Optional paper when the subject has multiple papers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='academics.subjectpaper'),
        ),
    ]
