# Generated by Django 5.2.15 on 2026-07-07 09:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def publish_existing_exams(apps, schema_editor):
    Exam = apps.get_model("examinations", "Exam")
    Exam.objects.all().update(lifecycle_status="published")


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_phase2_academic_workflows'),
        ('examinations', '0002_exam_paper'),
        ('tenants', '0004_school_role_feature_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='lifecycle_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='marks_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='marks_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_approved_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='marks_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='marks_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_locked_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='marks_reopen_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='marks_reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='marks_reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_reopened_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='marks_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('locked', 'Locked')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='marks_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='marks_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_submitted_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='entry_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('locked', 'Locked')], db_index=True, default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ExaminationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('closed', 'Closed')], db_index=True, default='planned', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_sessions', to='academics.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examination_sessions', to='academics.term')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='examination_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='examinations.examinationsession'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['tenant', 'school_class', 'term'], name='examination_tenant__93a1a4_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['tenant', 'lifecycle_status', 'marks_status'], name='examination_tenant__2af97c_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationsession',
            index=models.Index(fields=['tenant', 'academic_year', 'status'], name='examination_tenant__75c27e_idx'),
        ),
        migrations.RunPython(publish_existing_exams, migrations.RunPython.noop),
    ]
