# Generated by Django 5.2.15 on 2026-07-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='mpesa_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='currency',
            field=models.CharField(default='KES', max_length=3),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='fee_category',
            field=models.CharField(choices=[('tuition', 'Tuition'), ('boarding', 'Boarding'), ('transport', 'Transport'), ('meals', 'Meals'), ('activity', 'Activity / Clubs'), ('exam', 'Examination'), ('uniform', 'Uniform'), ('development', 'Development Levy'), ('other', 'Other')], default='tuition', max_length=30),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='frequency',
            field=models.CharField(choices=[('once', 'One-time'), ('termly', 'Per Term'), ('annual', 'Annual'), ('monthly', 'Monthly')], default='termly', max_length=20),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='vote_head_code',
            field=models.CharField(blank=True, help_text='Government vote head / account code', max_length=30),
        ),
    ]
