# Generated by Django 5.2.15 on 2026-07-03 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('school_admin', 'School Admin'), ('head_teacher', 'Head Teacher'), ('deputy_head_teacher', 'Deputy Head Teacher'), ('director_of_studies', 'Director of Studies'), ('head_of_department', 'Head of Department'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student'), ('bursar', 'Bursar / Accountant'), ('librarian', 'Librarian'), ('hr_manager', 'Human Resource Manager'), ('transport_manager', 'Transport Manager'), ('hostel_manager', 'Hostel Manager'), ('inventory_manager', 'Inventory Manager / Store Keeper'), ('finance_officer', 'Finance Officer (Legacy)'), ('hr_officer', 'HR Officer (Legacy)'), ('transport_officer', 'Transport Officer (Legacy)'), ('hostel_warden', 'Hostel Warden (Legacy)'), ('inventory_officer', 'Inventory Officer (Legacy)'), ('receptionist', 'Receptionist'), ('nurse', 'Nurse'), ('counselor', 'Counselor')], db_index=True, default='teacher', max_length=30),
        ),
        migrations.CreateModel(
            name='UserProfilePicture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='avatars/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile picture',
                'verbose_name_plural': 'user profile pictures',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
