# Generated by Django 5.2.15 on 2026-07-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='curriculum',
            field=models.CharField(choices=[('cbc', 'CBC'), ('844', '8-4-4'), ('igcse', 'IGCSE'), ('other', 'Other')], default='cbc', max_length=20),
        ),
        migrations.AddField(
            model_name='class',
            name='level_type',
            field=models.CharField(blank=True, choices=[('pre_primary', 'Pre-Primary'), ('primary', 'Primary'), ('junior_secondary', 'Junior Secondary'), ('senior_secondary', 'Senior Secondary'), ('tertiary', 'Tertiary')], max_length=30),
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, help_text='Section label e.g. A, B, East', max_length=20),
        ),
        migrations.AddField(
            model_name='term',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='mid_term_break_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='mid_term_break_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='reporting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='term_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1, 2, or 3 for Kenyan terms', null=True),
        ),
    ]
