import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0010_timetable_generation"),
        ("students", "0003_ea_context_fields"),
        ("accounts", "0003_user_must_change_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="curriculum",
            field=models.CharField(
                choices=[
                    ("uneb", "UNEB (Uganda)"),
                    ("uganda_cbe", "Uganda Competence-Based"),
                    ("cbc", "CBC (Kenya)"),
                    ("844", "8-4-4"),
                    ("igcse", "IGCSE"),
                    ("ace", "ACE"),
                    ("other", "Other"),
                ],
                default="uneb",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="term_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="1, 2, or 3 for East African term calendars (Uganda default)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teachingassignment",
            name="term",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional term scope for mid-year staffing history.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_assignments",
                to="academics.term",
            ),
        ),
        migrations.CreateModel(
            name="StudentAcademicPlacement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(db_index=True, default="active", max_length=20)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("enrolled_on", models.DateField(blank=True, null=True)),
                ("ended_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("academic_year", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="student_placements", to="academics.academicyear")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("school_class", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="student_placements", to="academics.class")),
                ("stream", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="student_placements", to="academics.stream")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="academic_placements", to="students.student")),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="tenants.tenant")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-academic_year__start_date", "student__last_name"]},
        ),
        migrations.CreateModel(
            name="PromotionBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(db_index=True, default="draft", max_length=20)),
                ("mapping", models.JSONField(blank=True, default=dict)),
                ("preview", models.JSONField(blank=True, default=dict)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("academic_year", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="promotion_batches", to="academics.academicyear")),
                ("committed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="committed_promotions", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("default_target_class", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="target_promotion_batches", to="academics.class")),
                ("default_target_stream", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="target_promotion_batches", to="academics.stream")),
                ("source_class", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="source_promotion_batches", to="academics.class")),
                ("source_stream", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="source_promotion_batches", to="academics.stream")),
                ("target_academic_year", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="incoming_promotion_batches", to="academics.academicyear")),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="tenants.tenant")),
                ("undone_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="undone_promotions", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="PromotionAction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("action", models.CharField(default="promote", max_length=20)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("applied", models.BooleanField(default=False)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="actions", to="academics.promotionbatch")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("from_class", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="academics.class")),
                ("from_stream", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="academics.stream")),
                ("placement", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="promotion_actions", to="academics.studentacademicplacement")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="promotion_actions", to="students.student")),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="tenants.tenant")),
                ("to_class", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="academics.class")),
                ("to_stream", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="academics.stream")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["student__last_name", "student__first_name"]},
        ),
        migrations.CreateModel(
            name="StudentSubjectRegistration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("combination_code", models.CharField(blank=True, max_length=40)),
                ("is_core", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("academic_year", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subject_registrations", to="academics.academicyear")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subject_registrations", to="students.student")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="student_registrations", to="academics.subject")),
                ("term", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="subject_registrations", to="academics.term")),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="tenants.tenant")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["subject__name"]},
        ),
        migrations.CreateModel(
            name="AssessmentScheme",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("components", models.JSONField(blank=True, default=list)),
                ("paper_aggregation", models.CharField(default="average", max_length=20)),
                ("use_division_bands", models.BooleanField(default=False)),
                ("division_bands", models.JSONField(blank=True, default=list)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="tenants.tenant")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AlterUniqueTogether(
            name="studentacademicplacement",
            unique_together={("tenant", "student", "academic_year", "school_class", "stream")},
        ),
        migrations.AlterUniqueTogether(
            name="promotionaction",
            unique_together={("tenant", "batch", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="studentsubjectregistration",
            unique_together={("tenant", "student", "academic_year", "term", "subject")},
        ),
        migrations.AlterUniqueTogether(
            name="assessmentscheme",
            unique_together={("tenant", "name")},
        ),
    ]
