# Generated by Django 5.2.15 on 2026-06-30 21:24

import apps.tenants.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Short school code', max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.tenants.models.tenant_upload_path)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=apps.tenants.models.tenant_upload_path)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=apps.tenants.models.tenant_upload_path)),
                ('login_bg', models.ImageField(blank=True, null=True, upload_to=apps.tenants.models.tenant_upload_path)),
                ('primary_color', models.CharField(default='#0F766E', max_length=7)),
                ('secondary_color', models.CharField(default='#FF7F50', max_length=7)),
                ('accent_color', models.CharField(default='#F5E6CA', max_length=7)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(db_index=True, default=False)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'is_suspended'], name='tenants_ten_status_1f43dd_idx'), models.Index(fields=['country', 'city'], name='tenants_ten_country_c9c9ba_idx')],
            },
        ),
    ]
