# Generated by Django 5.2.15 on 2026-07-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='payment_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='registration_type',
            field=models.CharField(choices=[('pending', 'Onboarding Pending'), ('trial_email', 'Trial via Email'), ('trial_plan', 'Trial Plan Selected'), ('paid', 'Paid Registration')], db_index=True, default='pending', max_length=20),
        ),
    ]
