# Generated by Django 5.2.15 on 2026-07-03 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_school_role_module_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRoleFeaturePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('school_admin', 'School Admin'), ('head_teacher', 'Head Teacher'), ('deputy_head_teacher', 'Deputy Head Teacher'), ('director_of_studies', 'Director of Studies'), ('head_of_department', 'Head of Department'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student'), ('bursar', 'Bursar / Accountant'), ('librarian', 'Librarian'), ('hr_manager', 'Human Resource Manager'), ('transport_manager', 'Transport Manager'), ('hostel_manager', 'Hostel Manager'), ('inventory_manager', 'Inventory Manager / Store Keeper'), ('finance_officer', 'Finance Officer (Legacy)'), ('hr_officer', 'HR Officer (Legacy)'), ('transport_officer', 'Transport Officer (Legacy)'), ('hostel_warden', 'Hostel Warden (Legacy)'), ('inventory_officer', 'Inventory Officer (Legacy)'), ('receptionist', 'Receptionist'), ('nurse', 'Nurse'), ('counselor', 'Counselor')], db_index=True, max_length=30)),
                ('feature_key', models.CharField(db_index=True, max_length=80)),
                ('can_read', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role', 'feature_key'],
            },
        ),
        migrations.RenameIndex(
            model_name='schoolrolemodulepermission',
            new_name='tenants_sch_tenant__6543a4_idx',
            old_name='tenants_sch_tenant__a8e2c1_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolrolemodulepermission',
            new_name='tenants_sch_tenant__f5f0d4_idx',
            old_name='tenants_sch_tenant__f4b9d2_idx',
        ),
        migrations.AddField(
            model_name='schoolrolefeaturepermission',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_feature_permissions', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='schoolrolefeaturepermission',
            index=models.Index(fields=['tenant', 'role'], name='tenants_sch_tenant__3aa4de_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolrolefeaturepermission',
            index=models.Index(fields=['tenant', 'feature_key'], name='tenants_sch_tenant__64566d_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolrolefeaturepermission',
            constraint=models.UniqueConstraint(fields=('tenant', 'role', 'feature_key'), name='uniq_tenant_role_feature_permission'),
        ),
    ]
