# Generated by Django 5.2.15 on 2026-07-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_school_role_feature_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolrolefeaturepermission',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('school_admin', 'School Admin'), ('head_teacher', 'Head Teacher'), ('deputy_head_teacher', 'Deputy Head Teacher'), ('director_of_studies', 'Director of Studies'), ('head_of_department', 'Head of Department'), ('teacher', 'Teacher'), ('class_teacher', 'Class Teacher'), ('parent', 'Parent'), ('student', 'Student'), ('bursar', 'Bursar / Accountant'), ('assistant_bursar', 'Assistant Bursar'), ('librarian', 'Librarian'), ('hr_manager', 'Human Resource Manager'), ('transport_manager', 'Transport Manager'), ('hostel_manager', 'Hostel Manager'), ('inventory_manager', 'Inventory Manager / Store Keeper'), ('finance_officer', 'Finance Officer (Legacy)'), ('hr_officer', 'HR Officer (Legacy)'), ('transport_officer', 'Transport Officer (Legacy)'), ('hostel_warden', 'Hostel Warden (Legacy)'), ('inventory_officer', 'Inventory Officer (Legacy)'), ('receptionist', 'Receptionist'), ('nurse', 'Nurse'), ('counselor', 'Counselor')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='schoolrolemodulepermission',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('school_admin', 'School Admin'), ('head_teacher', 'Head Teacher'), ('deputy_head_teacher', 'Deputy Head Teacher'), ('director_of_studies', 'Director of Studies'), ('head_of_department', 'Head of Department'), ('teacher', 'Teacher'), ('class_teacher', 'Class Teacher'), ('parent', 'Parent'), ('student', 'Student'), ('bursar', 'Bursar / Accountant'), ('assistant_bursar', 'Assistant Bursar'), ('librarian', 'Librarian'), ('hr_manager', 'Human Resource Manager'), ('transport_manager', 'Transport Manager'), ('hostel_manager', 'Hostel Manager'), ('inventory_manager', 'Inventory Manager / Store Keeper'), ('finance_officer', 'Finance Officer (Legacy)'), ('hr_officer', 'HR Officer (Legacy)'), ('transport_officer', 'Transport Officer (Legacy)'), ('hostel_warden', 'Hostel Warden (Legacy)'), ('inventory_officer', 'Inventory Officer (Legacy)'), ('receptionist', 'Receptionist'), ('nurse', 'Nurse'), ('counselor', 'Counselor')], db_index=True, max_length=30),
        ),
    ]
