# Generated by Django 5.2.15 on 2026-07-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_profile_expansion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='parent',
            new_name='students_pa_tenant__9645f0_idx',
            old_name='students_pa_tenant__c4e8a1_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_tenant__573062_idx',
            old_name='students_st_tenant__7d2f9b_idx',
        ),
        migrations.AddField(
            model_name='parent',
            name='consent_for_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parent',
            name='is_fee_payer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parent',
            name='mpesa_phone',
            field=models.CharField(blank=True, help_text='M-Pesa number for fee payments', max_length=20),
        ),
        migrations.AddField(
            model_name='parent',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='parent',
            name='sub_county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_certificate_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='boarding_status',
            field=models.CharField(choices=[('day', 'Day Scholar'), ('boarding', 'Boarding'), ('weekly', 'Weekly Boarding')], default='day', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='curriculum_pathway',
            field=models.CharField(blank=True, choices=[('cbc', 'CBC'), ('844', '8-4-4'), ('igcse', 'IGCSE'), ('ace', 'ACE'), ('other', 'Other')], default='cbc', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='special_needs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='special_needs_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sub_county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='upi_number',
            field=models.CharField(blank=True, db_index=True, help_text='NEMIS Unique Personal Identifier (UPI)', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='ward',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
