"""Examination workflow constants."""
from __future__ import annotations

EXAM_LIFECYCLE_DRAFT = "draft"
EXAM_LIFECYCLE_PUBLISHED = "published"
EXAM_LIFECYCLE_ARCHIVED = "archived"

EXAM_LIFECYCLE_CHOICES = [
    (EXAM_LIFECYCLE_DRAFT, "Draft"),
    (EXAM_LIFECYCLE_PUBLISHED, "Published"),
    (EXAM_LIFECYCLE_ARCHIVED, "Archived"),
]

MARKS_STATUS_DRAFT = "draft"
MARKS_STATUS_SUBMITTED = "submitted"
MARKS_STATUS_APPROVED = "approved"
MARKS_STATUS_LOCKED = "locked"

MARKS_STATUS_CHOICES = [
    (MARKS_STATUS_DRAFT, "Draft"),
    (MARKS_STATUS_SUBMITTED, "Submitted"),
    (MARKS_STATUS_APPROVED, "Approved"),
    (MARKS_STATUS_LOCKED, "Locked"),
]

GRADE_ENTRY_STATUS_CHOICES = MARKS_STATUS_CHOICES

EXAMINATION_SESSION_PLANNED = "planned"
EXAMINATION_SESSION_ACTIVE = "active"
EXAMINATION_SESSION_CLOSED = "closed"

EXAMINATION_SESSION_STATUS_CHOICES = [
    (EXAMINATION_SESSION_PLANNED, "Planned"),
    (EXAMINATION_SESSION_ACTIVE, "Active"),
    (EXAMINATION_SESSION_CLOSED, "Closed"),
]

MARKS_EDITABLE_STATUSES = frozenset({MARKS_STATUS_DRAFT, MARKS_STATUS_SUBMITTED})